version: "3.8"
services:

  postgres-book:
    image: "postgres:13"
    container_name: "postgres-book"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bookdb
    volumes:
      - postgres-book-data:/var/lib/postgresql/data

  postgres-order:
    image: "postgres:13"
    container_name: "postgres-order"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=orderdb
    volumes:
      - postgres-order-data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:13.0.0
    container_name: "keycloak"
    volumes:
      - ./platform-config/keycloak:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080

volumes:
  postgres-book-data:
    name: postgres-book-data
  postgres-order-data:
    name: postgres-order-data
