global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'book-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'kubernetes.docker.internal:8001' ]
        labels:
          application: 'book-service'
  - job_name: 'order-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'kubernetes.docker.internal:8002' ]
        labels:
          application: 'order-service'
  - job_name: 'edge-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'kubernetes.docker.internal:9000' ]
        labels:
          application: 'edge-service'
  - job_name: 'config-server'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'kubernetes.docker.internal:8888' ]
        labels:
          application: 'config-server'
  - job_name: 'eureka-server'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'kubernetes.docker.internal:8761' ]
        labels:
          application: 'eureka-server'
