server:
  port: 8001

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: admin
    password: admin
  profiles:
    active: test-data
